import Button from "@/components/Button";
import Head from "next/head";
import Link from "next/link";
import { HiOutlineMenu, HiPlay } from "react-icons/hi"

export default function Home() {
  return (
    <div>
      <Head>
        <title>React Pro Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-screen h-[80px]">
        <div className="w-full h-full max-w-7xl m-auto flex items-center justify-between px-5 border-b border-b-slate-800">
          <div className="flex items-center gap-2">
            <HiPlay className="text-green-400" size={30} />
            <p className="text-green-400 font-bold text-xl">
              React Pro Player
            </p>
          </div>
          <nav className="hidden lg:block">
            <ul className="flex items-center gap-5">
              <li>
                <Link href="/" className={styles.navLink}>Features</Link>
              </li>
              <li>
                <Link href="/" className={styles.navLink}>Pricing</Link>
              </li>
            </ul>
          </nav>
          <div className="hidden lg:block">
            <Button label="Contact" />
          </div>
          <HiOutlineMenu className="lg:hidden" size={30} />
        </div>
      </header>

      <section className="py-20">
        <div className="px-5">
          <div className="text-center flex flex-col gap-5 max-w-4xl m-auto">
            <h1 className="lg:text-5xl text-3xl font-medium">Play HLS & DASH streams with our advanced web video player</h1>
            <p className="opacity-80">Test your HLS (M3U8), DASH stream urls with our player</p>
          </div>
          <div className="flex gap-3 items-center justify-center mt-10">
            <input className="w-full bg-transparent bg-white outline-none border-none text-black p-2 px-3 rounded-md max-w-xl" placeholder="Enter an HLS or DASH url to test player" />
            <Button label="Play" />
          </div>
        </div>
      </section>
    </div>
  )
}

const styles = {
  navLink: `hover:text-brand transition-all`
}
